# Generated by Django 3.0.8 on 2020-07-10 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your name', max_length=20)),
                ('second_name', models.CharField(help_text='Your sec name', max_length=20)),
                ('age', models.PositiveSmallIntegerField(help_text="Yuor age! yep, not a birth's day")),
                ('country', models.CharField(choices=[('RU', 'Russian Federation'), ('WORLD', 'Not Russian'), ('KZ', 'Kazakstan')], default='RU', max_length=5)),
                ('city', models.CharField(help_text='You live', max_length=20)),
                ('about', models.TextField()),
                ('image', models.ImageField(default='avatars/default.png', upload_to='images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', '-second_name'],
            },
        ),
    ]
