# Generated by Django 3.0.8 on 2020-07-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your name', max_length=20)),
                ('second_name', models.CharField(help_text='Your sec name', max_length=20)),
                ('age', models.PositiveSmallIntegerField(help_text="Yuor age! yep, not a birth's day")),
                ('country', models.CharField(choices=[('RU', 'Russian Federation'), ('WORLD', 'Not Russian'), ('KZ', 'Kazakstan')], default='RU', max_length=5)),
                ('city', models.CharField(help_text='You live', max_length=20)),
                ('about', models.TextField()),
            ],
            options={
                'ordering': ['name', '-second_name'],
            },
        ),
    ]
