# Generated by Django 3.0.8 on 2020-07-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveSmallIntegerField(default=0, help_text="Yuor age! yep, not a birth's day"),
        ),
    ]
