# Generated by Django 3.0.8 on 2020-07-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
